{% set name = "attune" %}
{% set version = "0.5.1" %}
{% set sha256 = "d67d3db7c255143c4d1d8915396b77acae2d8b7ac316d9fbe8a56cc2fe64c10a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  entry_points:
    - attune = attune._cli:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >={{ python_min }}
    - WrightTools >=3.2.5
    - numpy
    - scipy
    - matplotlib-base
    - appdirs
    - dateparser
    - python-dateutil
    - click

test:
  imports:
    - attune
  commands:
    - pip check
    - attune --help
  requires:
    - python {{ python_min }}
    - pip  

about:
  home: https://github.com/wright-group/attune
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for tuning optical parametric amplifiers and multidimensional spectrometers.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - darienmorrow
    - kameyer226
    - ddkohler
