{% set name = "attune" %}
{% set version = "0.5.0" %}
{% set sha256 = "8ba17659683d9c064074d4c630d2c153d9999e6a6c4f2eb1331bce2a18efd18a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >=3.6
    - WrightTools >=3.2.5
    - numpy
    - scipy
    - matplotlib-base
    - appdirs
    - maya
    - python-dateutil

test:
  imports:
    - attune

about:
  home: https://github.com/wright-group/attune
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for tuning optical parametric amplifiers and multidimensional spectrometers.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
    - darienmorrow
    - kameyer226
    - ddkohler
